version: '3.8'
services:
  okrika-backend:
    build: .
    container_name: okrika-backend
    depends_on:
      - dev-db
    ports:
      - '3000:3000'
    networks:
      - default

  dev-db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    name: okrika-network
    driver: bridge